export const defaultVisibility = {
  title: true,
  description: true,
  imageUrl: true,
  githubUrl: true,
  liveUrl: true,
  technologies: true,
  status: true,
  language: true,
  topics: true,
  starsCount: true,
  forksCount: true,
  watchersCount: true,
  homepageUrl: true,
};

export const defaultFormData = {
  id: undefined,
  title: '',
  description: '',
  imageUrl: '',
  githubUrl: '',
  liveUrl: '',
  technologies: [],
  status: 'WIP',
  topics: [],
  starsCount: 0,
  forksCount: 0,
  watchersCount: 0,
  homepageUrl: '',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  details: {
    languages_map: {},
    fields_visibility: defaultVisibility
  },
  own_description: '',
  short_description: '',
  highlight: '',
  learnings: '',
  challenges: '',
  role: '',
  custom_tags: [],
  is_public: true,
  team: [],
  screenshots: [],
  links: {},
};

export const defaultOverrideState = {
  title: false,
  description: false,
  own_description: false,
  short_description: false,
  highlight: false,
  learnings: false,
  challenges: false,
  role: false,
}; 