forest_mist_theme = {
    "name": "Forest Mist",
    "description": "A tranquil, nature-inspired green theme",
    "style_properties": {
        "colors": {
            "primary": "#22c55e",
            "secondary": "#16a34a",
            "accent": "#a3e635",
            "background": "#f0fdf4",
            "text": "#212529",
            "cardBg": "#e6f9ec",
            "cardBorder": "#22c55e33",
            "cardShadow": "0 4px 24px rgba(34, 197, 94, 0.10)",
            "navbarBg": "rgba(34,197,94,0.8)",
            "navbarText": "#14532d",
            "navbarBorder": "#22c55e33",
            "navbarButtonBg": "#16a34a",
            "navbarButtonText": "#fff",
            "navbarButtonHoverBg": "#a3e635",
            "navbarButtonHoverText": "#14532d",
            "navbarLinkHoverBg": "#bbf7d0",
            "navbarLinkActiveBg": "#22c55e",
            "navbarLinkActiveText": "#fff",
            "link": "#22c55e",
            "aboutImageBorder": "#16a34a",
            "aboutTitle": "#14532d",
            "aboutText": "#166534",
            "aboutListIcon": "#22c55e",
            "aboutListLink": "#166534",
            "backgroundStart": "#14532d",
            "backgroundEnd": "#166534",
            "cardTitle": "#14532d",
            "cardText": "#166534",
            "cardListItem": "#166534",
            "cardListIcon": "#22c55e",
            "buttonBg": "#16a34a",
            "buttonText": "#fff",
            "buttonBorder": "#22c55e",
            "buttonShadow": "0 2px 8px rgba(22,163,74,0.08)",
            "buttonHoverBg": "#a3e635",
            "buttonHoverText": "#14532d",
            "sectionHeading": "#14532d",
            "sectionParagraph": "#166534",
            "sectionLink": "#22c55e",
            "aboutContentMinWidth": "280px",
            "aboutImageBoxShadow": "0 4px 24px rgba(34,197,94,0.15)",
            "cardShadowHover": "0 4px 24px rgba(34,197,94,0.18)",
            "cardBorderHover": "#22c55e55",
            "success": "#16a34a",
            "successForeground": "#ffffff",
            "successHoverBackground": "#15803d",
            "warning": "#facc15",
            "warningForeground": "#1e293b",
            "warningHoverBackground": "#fbbf24",
            "mutedHoverBackground": "#94a3b8",
            "muted": "#94a3b8",
            "mutedForeground": "#64748b",
            "destructive": "#ef4444",
            "destructiveForeground": "#fff",
            "destructiveHoverBackground": "#dc2626",
            "border": "#16a34a",
            "borderHSL": "145 52% 18%",
            "card": "#e6f9ec",
            "cardForeground": "#14532d",
            "popover": "#e6f9ec",
            "popoverForeground": "#14532d",
            "ring": "#22c55e",
            "inputBorder": "#16a34a",
            "foreground": "#212529"
        },
        "typography": {
            "fontFamily": "Lato, sans-serif",
            "fontSize": "16px",
            "fontWeight": "400",
            "fontWeightBold": "700",
            "lineHeight": "1.6",
            "navbarFontSize": "1rem",
            "navbarFontWeight": "500",
            "cardTitleFontSize": "1.25rem",
            "cardTextFontSize": "1rem",
            "aboutTitleFontSize": "2.5rem",
            "aboutTitleFontWeight": "bold",
            "aboutTextFontSize": "1.15rem",
            "aboutListIconFontSize": "22px"
        },
        "spacing": {
            "small": "0.3rem",
            "medium": "0.8rem",
            "large": "1.8rem",
            "sectionPadding": "60px 0",
            "containerGap": "48px",
            "containerMaxWidth": "1200px",
            "containerPadding": "0 24px",
            "navbarPadding": "0 1rem",
            "navbarHeight": "4rem",
            "navbarLinkPadding": "0.5rem 1rem",
            "navbarButtonPadding": "0.5rem 1.25rem",
            "cardPadding": "1.5rem",
            "aboutTitleMarginBottom": "24px",
            "aboutTextMarginBottom": "24px",
            "aboutListGap": "16px",
            "aboutListItemGap": "12px"
        },
        "borderRadius": {
            "small": "0.18rem",
            "medium": "0.36rem",
            "large": "0.72rem",
            "full": "9999px",
            "navbar": "0.5rem",
            "card": "1rem",
            "button": "0.5rem",
            "aboutImage": "24px"
        },
        "shadows": {
            "card": "0 4px 24px rgba(34,197,94,0.10)",
            "cardHover": "0 4px 24px rgba(34,197,94,0.18)",
            "button": "0 2px 8px rgba(22,163,74,0.08)"
        },
        "cardBlur": "4px",
        "cardRadius": "1rem",
        "cardListGap": "16px",
        "cardListItemGap": "12px",
        "cardListIconFontSize": "22px"
    }
}
