galaxy_theme = {
    "name": "Galaxy",
    "description": "A cosmic galaxy theme",
    "style_properties": {
        "colors": {
            "primary": "#a78bfa",
            "secondary": "#6366f1",
            "accent": "#f472b6",
            "background": "#0f172a",
            "text": "#f1f5f9",
            "cardBg": "rgba(30,41,59,0.5)",
            "cardBorder": "#a78bfa33",
            "cardShadow": "0 4px 24px rgba(167,139,250,0.1)",
            "navbarBg": "rgba(15,23,42,0.8)",
            "navbarText": "#b0b0b0",
            "navbarBorder": "#a78bfa33",
            "navbarButtonBg": "#7c3aed",
            "navbarButtonText": "#fff",
            "navbarButtonHoverBg": "#a78bfa",
            "navbarButtonHoverText": "#fff",
            "navbarLinkHoverBg": "#7c3aed33",
            "navbarLinkActiveBg": "#7c3aed",
            "navbarLinkActiveText": "#fff",
            "link": "#a78bfa",
            "aboutImageBorder": "#7c3aed",
            "aboutTitle": "#fff",
            "aboutText": "#b0b0b0",
            "aboutListIcon": "#a78bfa",
            "aboutListLink": "#b0b0b0",
            "backgroundStart": "rgb(2, 6, 23)",
            "backgroundEnd": "rgb(15, 23, 42)",
            "cardTitle": "#fff",
            "cardText": "#b0b0b0",
            "cardListItem": "#b0b0b0",
            "cardListIcon": "#a78bfa",
            "sectionLink": "#a78bfa",
            "sectionHeading": "#fff",
            "sectionParagraph": "#b0b0b0",
            "buttonBg": "#03afee",
            "buttonText": "#fff",
            "buttonBorder": "transparent",
            "buttonShadow": "0 2px 8px rgba(124,58,237,0.08)",
            "buttonHoverBg": "#a78bfa",
            "buttonHoverText": "#fff",
            "aboutContentMinWidth": "280px",
            "aboutImageBoxShadow": "0 4px 24px rgba(0,0,0,0.15)",
            "cardShadowHover": "0 4px 24px rgba(167,139,250,0.2)",
            "cardBorderHover": "#a78bfa55",
            "success": "#16a34a",
            "successForeground": "#ffffff",
            "successHoverBackground": "#15803d",
            "warning": "#fde047",
            "warningForeground": "#1e293b",
            "warningHoverBackground": "#facc15",
            "mutedHoverBackground": "#9ca3af",
            "textGradient": "linear-gradient(to right, #a78bfa, #f472b6, #60a5fa)"
        },
        "typography": {
            "fontFamily": "Inter, sans-serif",
            "fontSize": "16px",
            "fontWeight": "400",
            "fontWeightBold": "700",
            "lineHeight": "1.6",
            "navbarFontSize": "1rem",
            "navbarFontWeight": "500",
            "cardTitleFontSize": "1.25rem",
            "cardTextFontSize": "1rem",
            "aboutTitleFontSize": "2.5rem",
            "aboutTitleFontWeight": "bold",
            "aboutTextFontSize": "1.15rem",
            "aboutListIconFontSize": "22px"
        },
        "spacing": {
            "small": "0.5rem",
            "medium": "1rem",
            "large": "2rem",
            "sectionPadding": "60px 0",
            "containerGap": "48px",
            "containerMaxWidth": "1200px",
            "containerPadding": "0 24px",
            "navbarPadding": "0 1rem",
            "navbarHeight": "4rem",
            "navbarLinkPadding": "0.5rem 1rem",
            "navbarButtonPadding": "0.5rem 1.25rem",
            "cardPadding": "1.5rem",
            "aboutTitleMarginBottom": "24px",
            "aboutTextMarginBottom": "24px",
            "aboutListGap": "16px",
            "aboutListItemGap": "12px"
        },
        "borderRadius": {
            "small": "0.25rem",
            "medium": "0.5rem",
            "large": "1rem",
            "full": "9999px",
            "navbar": "0.5rem",
            "card": "1rem",
            "button": "0.5rem",
            "aboutImage": "24px"
        },
        "shadows": {
            "card": "0 4px 24px rgba(167,139,250,0.1)",
            "cardHover": "0 4px 24px rgba(167,139,250,0.2)",
            "button": "0 2px 8px rgba(124,58,237,0.08)"
        },
        "cardBlur": "4px",
        "cardRadius": "1rem",
        "cardListGap": "16px",
        "cardListItemGap": "12px",
        "cardListIconFontSize": "22px"
    }
}
