ocean_breeze_theme = {
    "name": "Ocean Breeze",
    "description": "A fresh and calming ocean-inspired theme",
    "style_properties": {
        "colors": {
            "primary": "#38bdf8",
            "secondary": "#0ea5e9",
            "accent": "#22d3ee",
            "background": "#e0f2fe",
            "text": "#0f172a",
            "cardBg": "rgba(255,255,255,0.8)",
            "cardBorder": "#38bdf833",
            "cardShadow": "0 4px 24px rgba(56,189,248,0.1)",
            "navbarBg": "rgba(224,242,254,0.8)",
            "navbarText": "#0f172a",
            "navbarBorder": "#38bdf833",
            "navbarButtonBg": "#0ea5e9",
            "navbarButtonText": "#fff",
            "navbarButtonHoverBg": "#38bdf8",
            "navbarButtonHoverText": "#fff",
            "navbarLinkHoverBg": "#38bdf833",
            "navbarLinkActiveBg": "#0ea5e9",
            "navbarLinkActiveText": "#fff",
            "link": "#0ea5e9",
            "aboutImageBorder": "#0ea5e9",
            "aboutTitle": "#0f172a",
            "aboutText": "#334155",
            "aboutListIcon": "#0ea5e9",
            "aboutListLink": "#334155",
            "backgroundStart": "#e0f2fe",
            "backgroundEnd": "#bae6fd",
            "cardTitle": "#0f172a",
            "cardText": "#334155",
            "cardListItem": "#334155",
            "cardListIcon": "#0ea5e9",
            "sectionLink": "#0ea5e9",
            "sectionHeading": "#0f172a",
            "sectionParagraph": "#334155",
            "buttonBg": "#0ea5e9",
            "buttonText": "#fff",
            "buttonBorder": "transparent",
            "buttonShadow": "0 2px 8px rgba(14,165,233,0.08)",
            "buttonHoverBg": "#38bdf8",
            "buttonHoverText": "#fff",
            "aboutContentMinWidth": "280px",
            "aboutImageBoxShadow": "0 4px 24px rgba(0,0,0,0.1)",
            "cardShadowHover": "0 4px 24px rgba(56,189,248,0.2)",
            "cardBorderHover": "#38bdf855",
            "success": "#16a34a",
            "successForeground": "#ffffff",
            "successHoverBackground": "#15803d",
            "warning": "#facc15",
            "warningForeground": "#1e293b",
            "warningHoverBackground": "#fbbf24",
            "mutedHoverBackground": "#94a3b8",
            "textGradient": "linear-gradient(to right, #38bdf8, #0ea5e9, #22d3ee)"
        },
        "typography": {
            "fontFamily": "Roboto, sans-serif",
            "fontSize": "15px",
            "fontWeight": "400",
            "fontWeightBold": "700",
            "lineHeight": "1.5",
            "navbarFontSize": "1rem",
            "navbarFontWeight": "500",
            "cardTitleFontSize": "1.25rem",
            "cardTextFontSize": "1rem",
            "aboutTitleFontSize": "2.5rem",
            "aboutTitleFontWeight": "bold",
            "aboutTextFontSize": "1.15rem",
            "aboutListIconFontSize": "22px"
        },
        "spacing": {
            "small": "0.25rem",
            "medium": "0.75rem",
            "large": "1.5rem",
            "sectionPadding": "60px 0",
            "containerGap": "48px",
            "containerMaxWidth": "1200px",
            "containerPadding": "0 24px",
            "navbarPadding": "0 1rem",
            "navbarHeight": "4rem",
            "navbarLinkPadding": "0.5rem 1rem",
            "navbarButtonPadding": "0.5rem 1.25rem",
            "cardPadding": "1.5rem",
            "aboutTitleMarginBottom": "24px",
            "aboutTextMarginBottom": "24px",
            "aboutListGap": "16px",
            "aboutListItemGap": "12px"
        },
        "borderRadius": {
            "small": "0.2rem",
            "medium": "0.4rem",
            "large": "0.8rem",
            "full": "9999px",
            "navbar": "0.5rem",
            "card": "1rem",
            "button": "0.5rem",
            "aboutImage": "24px"
        },
        "shadows": {
            "card": "0 4px 24px rgba(56,189,248,0.1)",
            "cardHover": "0 4px 24px rgba(56,189,248,0.2)",
            "button": "0 2px 8px rgba(14,165,233,0.08)"
        },
        "cardBlur": "4px",
        "cardRadius": "1rem",
        "cardListGap": "16px",
        "cardListItemGap": "12px",
        "cardListIconFontSize": "22px"
    }
}
