solar_flare_theme = {
    "name": "Solar Flare",
    "description": "A vibrant, energetic theme inspired by the sun",
    "style_properties": {
        "colors": {
            "primary": "#fbbf24",
            "secondary": "#f59e42",
            "accent": "#f87171",
            "background": "#fff7ed",
            "text": "#7c2d12",
            "cardBg": "rgba(255,247,237,0.8)",
            "cardBorder": "#fbbf2433",
            "cardShadow": "0 4px 24px rgba(251,191,36,0.1)",
            "navbarBg": "rgba(255,247,237,0.8)",
            "navbarText": "#7c2d12",
            "navbarBorder": "#fbbf2433",
            "navbarButtonBg": "#f59e42",
            "navbarButtonText": "#fff",
            "navbarButtonHoverBg": "#fbbf24",
            "navbarButtonHoverText": "#7c2d12",
            "navbarLinkHoverBg": "#fbbf2433",
            "navbarLinkActiveBg": "#f59e42",
            "navbarLinkActiveText": "#fff",
            "link": "#f59e42",
            "aboutImageBorder": "#f59e42",
            "aboutTitle": "#7c2d12",
            "aboutText": "#9a3412",
            "aboutListIcon": "#f59e42",
            "aboutListLink": "#9a3412",
            "backgroundStart": "#fff7ed",
            "backgroundEnd": "#fed7aa",
            "cardTitle": "#7c2d12",
            "cardText": "#9a3412",
            "cardListItem": "#9a3412",
            "cardListIcon": "#f59e42",
            "sectionLink": "#f59e42",
            "sectionHeading": "#7c2d12",
            "sectionParagraph": "#9a3412",
            "buttonBg": "#f59e42",
            "buttonText": "#fff",
            "buttonBorder": "transparent",
            "buttonShadow": "0 2px 8px rgba(245,158,66,0.08)",
            "buttonHoverBg": "#fbbf24",
            "buttonHoverText": "#7c2d12",
            "aboutContentMinWidth": "280px",
            "aboutImageBoxShadow": "0 4px 24px rgba(0,0,0,0.1)",
            "cardShadowHover": "0 4px 24px rgba(251,191,36,0.2)",
            "cardBorderHover": "#fbbf2455",
            "success": "#16a34a",
            "successForeground": "#ffffff",
            "successHoverBackground": "#15803d",
            "warning": "#facc15",
            "warningForeground": "#1e293b",
            "warningHoverBackground": "#fbbf24",
            "mutedHoverBackground": "#94a3b8"
        },
        "typography": {
            "fontFamily": "Montserrat, sans-serif",
            "fontSize": "17px",
            "fontWeight": "400",
            "fontWeightBold": "700",
            "lineHeight": "1.7",
            "navbarFontSize": "1rem",
            "navbarFontWeight": "500",
            "cardTitleFontSize": "1.25rem",
            "cardTextFontSize": "1rem",
            "aboutTitleFontSize": "2.5rem",
            "aboutTitleFontWeight": "bold",
            "aboutTextFontSize": "1.15rem",
            "aboutListIconFontSize": "22px"
        },
        "spacing": {
            "small": "0.4rem",
            "medium": "1rem",
            "large": "2.5rem",
            "sectionPadding": "60px 0",
            "containerGap": "48px",
            "containerMaxWidth": "1200px",
            "containerPadding": "0 24px",
            "navbarPadding": "0 1rem",
            "navbarHeight": "4rem",
            "navbarLinkPadding": "0.5rem 1rem",
            "navbarButtonPadding": "0.5rem 1.25rem",
            "cardPadding": "1.5rem",
            "aboutTitleMarginBottom": "24px",
            "aboutTextMarginBottom": "24px",
            "aboutListGap": "16px",
            "aboutListItemGap": "12px"
        },
        "borderRadius": {
            "small": "0.3rem",
            "medium": "0.6rem",
            "large": "1.2rem",
            "full": "9999px",
            "navbar": "0.5rem",
            "card": "1rem",
            "button": "0.5rem",
            "aboutImage": "24px"
        },
        "shadows": {
            "card": "0 4px 24px rgba(251,191,36,0.1)",
            "cardHover": "0 4px 24px rgba(251,191,36,0.2)",
            "button": "0 2px 8px rgba(245,158,66,0.08)"
        },
        "cardBlur": "4px",
        "cardRadius": "1rem",
        "cardListGap": "16px",
        "cardListItemGap": "12px",
        "cardListIconFontSize": "22px"
    }
}
