#!/usr/bin/env node

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import scriptsConfig from '../../shared/scripts/config.js';

interface UserInfo {
  username: string;
  password: string;
  password_hint: string;
  root_username: string;
  root_password: string;
  root_password_hint: string;
}

interface PermissionRule {
  path: string;
  owner: string;
  group: string;
  permissions: {
    owner: { read: boolean; write: boolean; execute: boolean };
    group: { read: boolean; write: boolean; execute: boolean };
    other: { read: boolean; write: boolean; execute: boolean };
  };
}

interface PermissionRules {
  _comment: string;
  users: Record<string, {
    userId: string;
    groups: string[];
    permissions: {
      read: string[];
      write: string[];
      execute: string[];
    };
  }>;
  rules: PermissionRule[];
}

function generatePermissionRules(userInfo: UserInfo): PermissionRules {
  const homeDir = `/home/${userInfo.username}`;
  
  return {
    "_comment": "This file is automatically generated from terminal-user-info.json. Do not edit manually.",
    "users": {
      [userInfo.username]: {
        userId: userInfo.username,
        groups: ["users", "sudo"],
        permissions: {
          read: [
            homeDir,
            `${homeDir}/*`,
            "/tmp",
            "/usr/share",
            "/var/log",
            "/etc/nixos"
          ],
          write: [
            homeDir,
            `${homeDir}/*`,
            "/tmp"
          ],
          execute: [
            "/",
            "/home",
            homeDir,
            `${homeDir}/*`,
            "/usr/bin",
            "/bin",
            "/usr/local/bin",
            "/tmp"
          ]
        }
      },
      [userInfo.root_username]: {
        userId: userInfo.root_username,
        groups: ["root", "wheel"],
        permissions: {
          read: ["/"],
          write: ["/"],
          execute: ["/"]
        }
      }
    },
    "rules": [
      // User home directory
      {
        path: homeDir,
        owner: userInfo.username,
        group: "users",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: false, execute: true },
          other: { read: false, write: false, execute: false }
        }
      },
      // User home directory subdirectories
      {
        path: `${homeDir}/*`,
        owner: userInfo.username,
        group: "users",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: false, execute: true },
          other: { read: false, write: false, execute: false }
        }
      },
      // Root directory
      {
        path: "/root",
        owner: userInfo.root_username,
        group: "root",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: false, write: false, execute: false },
          other: { read: false, write: false, execute: false }
        }
      },
      // System directories
      {
        path: "/tmp",
        owner: userInfo.root_username,
        group: "root",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: true, execute: true },
          other: { read: true, write: true, execute: true }
        }
      },
      {
        path: "/usr/bin",
        owner: userInfo.root_username,
        group: "root",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: false, execute: true },
          other: { read: true, write: false, execute: true }
        }
      },
      {
        path: "/bin",
        owner: userInfo.root_username,
        group: "root",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: false, execute: true },
          other: { read: true, write: false, execute: true }
        }
      },
      {
        path: "/etc",
        owner: userInfo.root_username,
        group: "root",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: false, execute: true },
          other: { read: true, write: false, execute: true }
        }
      },
      {
        path: "/var/log",
        owner: userInfo.root_username,
        group: "root",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: false, execute: true },
          other: { read: true, write: false, execute: true }
        }
      },
      {
        path: "/usr/share",
        owner: userInfo.root_username,
        group: "root",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: false, execute: true },
          other: { read: true, write: false, execute: true }
        }
      },
      {
        path: "/etc/nixos",
        owner: userInfo.root_username,
        group: "root",
        permissions: {
          owner: { read: true, write: true, execute: true },
          group: { read: true, write: false, execute: true },
          other: { read: true, write: false, execute: true }
        }
      }
    ]
  };
}

function main(): void {
  console.log('🔐 Generating permission rules...');
  
  try {
    // Lade die terminal-user-info.json (aus terminal/ Ordner)
    const userInfoPath = path.join(__dirname, '../../frontend/public/data/terminal/terminal-user-info.json');
    
    if (!fs.existsSync(userInfoPath)) {
      console.error('❌ terminal-user-info.json not found!');
      console.log('💡 Run: node scripts/terminal-system/copy-user-info.js first');
      process.exit(1);
    }
    
    const userInfo: UserInfo = JSON.parse(fs.readFileSync(userInfoPath, 'utf8'));
    console.log(`👤 Using user info for: ${userInfo.username}`);
    
    // Generiere die Permission Rules
    const permissionRules = generatePermissionRules(userInfo);
    
    // Speichere als JSON
    // Schreibe in terminal/ Ordner
    const terminalDir = path.join(__dirname, '../../frontend/public/data/terminal');
    if (!fs.existsSync(terminalDir)) {
      fs.mkdirSync(terminalDir, { recursive: true });
    }
    const outputPath = path.join(terminalDir, 'permission-rules.json');
    fs.writeFileSync(outputPath, JSON.stringify(permissionRules, null, 2));
    
    console.log(`✅ Permission rules saved to: ${outputPath}`);
    console.log(`📋 Generated rules for user: ${userInfo.username}`);
    console.log(`📋 Generated rules for root: ${userInfo.root_username}`);
    
    console.log('\n🎯 Next steps:');
    console.log('1. Run: node scripts/terminal-system/copy-fake-os-structure.js');
    console.log('2. Run: node scripts/terminal-system/convert-os-structure-to-filesystem.js');
    
  } catch (error) {
    console.error('❌ Error generating permission rules:', error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

export { generatePermissionRules };
